#ifndef __CFontEditorGUI__
#define __CFontEditorGUI__

/**
@file
Subclass of CFontEditorGUIBase, which is generated by wxFormBuilder.
*/

#include "CFontEditorGUIBase.h"

//// end generated include

/** Implementing CFontEditorGUIBase */
class CFontEditorGUI : public CFontEditorGUIBase
{
	protected:
		// Handlers for CFontEditorGUIBase events.
		void m_gdFontListOnGridSelectCell( wxGridEvent& event );
		void m_gdFontListOnKeyDown( wxKeyEvent& event );
		void m_chFontStyleOnChoice( wxCommandEvent& event );
		void m_bpButton1OnButtonClick( wxCommandEvent& event );
		void m_lbFontSizeOnLeftDClick( wxMouseEvent& event );
		void m_bpButton2OnButtonClick( wxCommandEvent& event );
		void m_btLessStrokeOnButtonClick( wxCommandEvent& event );
		void m_lbStrokeSizeOnLeftDClick( wxMouseEvent& event );
		void m_btMoreStrokeOnButtonClick( wxCommandEvent& event );
		void m_gdSpecialCharsOnGridCmdCellLeftDClick( wxGridEvent& event );
		void m_gdSpecialCharsOnGridSelectCell( wxGridEvent& event );
		void m_btNewSCOnButtonClick( wxCommandEvent& event );
		void m_btEdiSCOnButtonClick( wxCommandEvent& event );
		void m_btDeleteSCOnButtonClick( wxCommandEvent& event );
		void ch_ConstraintsOnChoice( wxCommandEvent& event );
		void m_sldBorderPixelsOnCommandScroll( wxScrollEvent& event );
		void m_sldForcedTrackingOnCommandScroll( wxScrollEvent& event );
		void m_sldPointScaleOnCommandScroll( wxScrollEvent& event );
		void m_sldYOffsetOnCommandScroll( wxScrollEvent& event );
		void menuitem1OnMenuSelection( wxCommandEvent& event );
		void menuitem2OnMenuSelection( wxCommandEvent& event );
		void menuitem22OnMenuSelection( wxCommandEvent& event );
		void menuitem21OnMenuSelection( wxCommandEvent& event );
		void menuitem211OnMenuSelection( wxCommandEvent& event );
		void menuitemOnMenuSelection( wxCommandEvent& event );
	public:
		/** Constructor */
		CFontEditorGUI( wxWindow* parent );
	//// end generated class members



};

#endif // __CFontEditorGUI__
