#ifndef __CSpecialCharGUI__
#define __CSpecialCharGUI__

/**
@file
Subclass of CSpecialCharGUIBase, which is generated by wxFormBuilder.
*/

#include "CSpecialCharGUIBase.h"
class CSpecialChar;
//// end generated include

/** Implementing CSpecialCharGUIBase */
class CSpecialCharGUI : public CSpecialCharGUIBase
{
	protected:
		// Handlers for CSpecialCharGUIBase events.
		void CSpecialCharGUIBaseOnClose( wxCloseEvent& event );
		void m_button1OnButtonClick( wxCommandEvent& event );
		void m_button2OnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		CSpecialCharGUI( wxWindow* parent,CSpecialChar* _poSC);
	//// end generated class members
		CSpecialChar* m_poSC;
};

#endif // __CSpecialCharGUI__
