#ifndef __CActorEditorGUI__
#define __CActorEditorGUI__

/**
@file
Subclass of CActorEditorGUIBase, which is generated by wxFormBuilder.
*/

#include "CActorEditorGUIBase.h"

//// end generated include

/** Implementing CActorEditorGUIBase */
class CActorEditorGUI : public CActorEditorGUIBase
{
	protected:
		// Handlers for CActorEditorGUIBase events.
		void GUIOnClose( wxCloseEvent& event );
		void GUIOnIdle( wxIdleEvent& event );
		void m_pnDisplayOnKeyDown( wxKeyEvent& event );
		void m_pnDisplayOnKeyUp( wxKeyEvent& event );
		void m_pnDisplayOnLeftDown( wxMouseEvent& event );
		void m_pnDisplayOnLeftUp( wxMouseEvent& event );
		void m_pnDisplayOnMiddleDown( wxMouseEvent& event );
		void m_pnDisplayOnMiddleUp( wxMouseEvent& event );
		void m_pnDisplayOnMotion( wxMouseEvent& event );
		void m_pnDisplayOnMouseWheel( wxMouseEvent& event );
		void m_pnDisplayOnSize( wxSizeEvent& event );
		void m_edBackXOffsetOnSpinCtrl( wxSpinEvent& event );
		void m_edBackYOffsetOnSpinCtrl( wxSpinEvent& event );
		void m_edBackXScaleOnSpinCtrl( wxSpinEvent& event );
		void m_edBackYScaleOnSpinCtrl( wxSpinEvent& event );
		void m_cbEditModeOnChoice( wxCommandEvent& event );
		void m_btUndoOnButtonClick( wxCommandEvent& event );
		void m_btRedoOnButtonClick( wxCommandEvent& event );
		void sb_KeyFrameOnScroll( wxScrollEvent& event );
		void bt_AddKeyframeOnButtonClick( wxCommandEvent& event );
		void bt_DelKeyframeOnButtonClick( wxCommandEvent& event );
		void m_gdTimelineOnGridCellLeftClick( wxGridEvent& event );
		void m_gdTimelineOnGridCellRightClick( wxGridEvent& event );
		void m_gdTimelineOnGridLabelLeftClick( wxGridEvent& event );
		void m_gdTimelineOnGridLabelRightClick( wxGridEvent& event );
		void OnPlayAnimationClick( wxCommandEvent& event );
		void OnLoopAnimationClick( wxCommandEvent& event );
		void sld_AnimTimeOnCommandScroll( wxScrollEvent& event );
		void m_edAnimTimeOnSpinCtrl( wxSpinEvent& event );
		void m_edBoneXCoordOnSpinCtrl( wxSpinEvent& event );
		void m_edBoneYCoordOnSpinCtrl( wxSpinEvent& event );
		void m_button5OnButtonClick( wxCommandEvent& event );
		void m_poBoneNodesOnTreeSelChanged( wxTreeEvent& event );
		void m_edNodePosXOnSpinCtrl( wxSpinEvent& event );
		void m_edNodePosYOnSpinCtrl( wxSpinEvent& event );
		void m_sldNodeAngleOnCommandScroll( wxScrollEvent& event );
		void m_edNodeDepthOnSpinCtrl( wxSpinEvent& event );
		void m_cpSelectColorOnColourChanged( wxColourPickerEvent& event );
		void m_sldNodeAlphaOnCommandScroll( wxScrollEvent& event );
		void bt_LoadSpriteOnButtonClick( wxCommandEvent& event );
		void bt_ClearSpriteOnButtonClick( wxCommandEvent& event );
		void m_cbSpriteActionListOnChoice( wxCommandEvent& event );
		void m_menuItem121OnMenuSelection( wxCommandEvent& event );
		void m_menuItem131OnMenuSelection( wxCommandEvent& event );
		void m_menuItem1311OnMenuSelection( wxCommandEvent& event );
		void m_menuItem14OnMenuSelection( wxCommandEvent& event );
		void m_menuItem141OnMenuSelection( wxCommandEvent& event );
		void m_miPoseSelStateOnMenuSelection( wxCommandEvent& event );
		void m_miInsertPoseSelOnMenuSelection( wxCommandEvent& event );
		void m_miClearPoseSelOnMenuSelection( wxCommandEvent& event );
		void m_miDeletePoseSelOnMenuSelection( wxCommandEvent& event );
		void m_menuItem17OnMenuSelection( wxCommandEvent& event );
		void m_menuItem16OnMenuSelection( wxCommandEvent& event );
		void m_menuItem29OnMenuSelection( wxCommandEvent& event );
		void m_menuItem18OnMenuSelection( wxCommandEvent& event );
		void m_menuItem19OnMenuSelection( wxCommandEvent& event );
		void m_menuItem20OnMenuSelection( wxCommandEvent& event );
		void m_menuItem30OnMenuSelection( wxCommandEvent& event );
		void m_menuItem21OnMenuSelection( wxCommandEvent& event );
		void m_menuItem22OnMenuSelection( wxCommandEvent& event );
		void m_menuItem23OnMenuSelection( wxCommandEvent& event );
		void m_menuItem161OnMenuSelection( wxCommandEvent& event );
		void m_menuItem291OnMenuSelection( wxCommandEvent& event );
		void m_menuItem181OnMenuSelection( wxCommandEvent& event );
		void m_menuItem191OnMenuSelection( wxCommandEvent& event );
		void m_menuItem201OnMenuSelection( wxCommandEvent& event );
		void m_menuItem301OnMenuSelection( wxCommandEvent& event );
		void m_menuItem211OnMenuSelection( wxCommandEvent& event );
		void m_menuItem221OnMenuSelection( wxCommandEvent& event );
		void m_menuItem231OnMenuSelection( wxCommandEvent& event );
		void menuitem0OnMenuSelection( wxCommandEvent& event );
		void menuitem1OnMenuSelection( wxCommandEvent& event );
		void menuitem11OnMenuSelection( wxCommandEvent& event );
		void m_menuItem12OnMenuSelection( wxCommandEvent& event );
		void m_menuItem10OnMenuSelection( wxCommandEvent& event );
		void m_menuItem11OnMenuSelection( wxCommandEvent& event );
		void m_moRestartWithSkelDefOnMenuSelection( wxCommandEvent& event );
		void menuitem3OnMenuSelection( wxCommandEvent& event );
		void m_miUndoOnMenuSelection( wxCommandEvent& event );
		void m_miRedoOnMenuSelection( wxCommandEvent& event );
		void ReloadMaterialsClick( wxCommandEvent& event );
		void menuitem4OnMenuSelection( wxCommandEvent& event );
		void menuitem5OnMenuSelection( wxCommandEvent& event );
		void menuitem7SelectBackgroundColor( wxCommandEvent& event );
		void menuitem7OnMenuSelection( wxCommandEvent& event );
		void m_menuItem13OnMenuSelection( wxCommandEvent& event );
		void mo_AboutOnMenuSelection( wxCommandEvent& event );
	public:
		/** Constructor */
		CActorEditorGUI( wxWindow* parent );
	//// end generated class members






};

#endif // __CActorEditorGUI__
