#ifndef __CKFRMActorEditorGUI__
#define __CKFRMActorEditorGUI__

/**
@file
Subclass of CKFRMActorEditorGUIBase, which is generated by wxFormBuilder.
*/

#include "CKFRMActorEditorGUIBase.h"

//// end generated include

/** Implementing CKFRMActorEditorGUIBase */
class CKFRMActorEditorGUI : public CKFRMActorEditorGUIBase
{
	protected:
		// Handlers for CKFRMActorEditorGUIBase events.
		void CKFRMActorEditorGUIBaseOnClose( wxCloseEvent& event );
		void CKFRMActorEditorGUIBaseOnIdle( wxIdleEvent& event );
		void sb_KeyFrameOnScroll( wxScrollEvent& event );
		void cb_ShowBackgroundOnCheckBox( wxCommandEvent& event );
		void cb_ShowLabelsOnCheckBox( wxCommandEvent& event );
		void ReloadMaterialsClick( wxCommandEvent& event );
		void OnPlayAnimationClick( wxCommandEvent& event );
		void sld_AnimTimeOnCommandScroll( wxCommandEvent& event );
		void sld_HScaleOnCommandScroll( wxCommandEvent& event );
		void sld_VScaleOnCommandScroll( wxCommandEvent& event );
		void bt_LoadSpriteOnButtonClick( wxCommandEvent& event );
		void cbSpriteActionOnCombobox( wxCommandEvent& event );
		void sld_OfsOnCommandScroll( wxCommandEvent& event );
		void sld_YOfsOnCommandScroll( wxCommandEvent& event );
		void m_menuItem12OnMenuSelection( wxCommandEvent& event );
		void m_menuItem10OnMenuSelection( wxCommandEvent& event );
		void menuitem3OnMenuSelection( wxCommandEvent& event );
	public:
		/** Constructor */
		CKFRMActorEditorGUI( wxWindow* parent );
	//// end generated class members
	
};

#endif // __CKFRMActorEditorGUI__
